spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      filter:
        remove-non-proxy-headers:
          headers:
      routes:
        - id:  consumer-service
          uri: lb://consumer-service
          predicates:
            - Path=/consumer/**
          # StripPrefix=1，否则访问服务时会带上consumer
          filters:
            - StripPrefix=1
            - name: Hystrix
                args:
                  name: default
                  fallbackUri: forward:/defaultFallback

server:
  port: 5007


#注册中心地址
eureka:
  instance:
    instance-id: ${spring.cloud.client.ip-address} :${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.101.5:5001/eureka/,http://192.168.101.5:5000/eureka/ # 防止注册中心崩溃，向两个注册中心注册

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000
ribbon:
  ReadTimeout: 10000   #负载均衡超时时间，默认值5000
  ConnectTimeout: 10000 #ribbon请求连接的超时时间，默认值2000


